# -*- coding: utf-8 -*-
"""Q1 pt 1 Aman Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DEa1SBEtoEvaB_1_sDlVSKlnMOEdiAHJ
"""

import networkx as nx
from itertools import chain, combinations
import matplotlib.pyplot as plt

celegans_graph=nx.Graph()
f = open("/content/out.dimacs10-celegans_metabolic", "r")
lines = f.readlines()
lines.pop(0)
for line in lines:
    l = line.split()
    celegans_graph.add_edge(l[0],l[1])

fig=plt.figure(figsize=(50,50))
nx.draw(celegans_graph)
plt.show()

giant = max(nx.connected_components(celegans_graph), key=len)
Ng = len(giant)
print("The len of giant component is:" + str(len(giant)))
print("The len of celegans graph is:" + str(len(celegans_graph)))
N = len(celegans_graph)
ngbyn = Ng/N
print(ngbyn)

# upload the out.arenas-jazz file to the local filesystem
jazz_graph=nx.Graph()

with open('out.arenas-jazz','r') as f:
  lines=f.readlines()
lines.pop(0)
for line in lines:
  line=line.strip()
  lis=line.split('\t')
  if lis != '% sym unweighted':
    jazz_graph.add_edge(lis[0],lis[1])

fig=plt.figure(figsize=(50,50))
nx.draw(jazz_graph)
plt.show()

giant = max(nx.connected_components(jazz_graph), key=len)
Ng = len(giant)
print("The len of giant component is:" + str(len(giant)))
print("The len of Jazz Musicial graph is:" + str(len(jazz_graph)))
N = len(jazz_graph)
ngbyn = Ng/N
print(ngbyn)